export const FETCH_SELF = 'FETCH_SELF';

export const FETCH_GUILD_INFO = 'FETCH_GUILD_INFO';

export const FETCH_RECENT_PUNISHMENTS = 'FETCH_RECENT_PUNISHMENTS';


export const FETCH_ADMINS = 'FETCH_ADMINS';
export const FETCH_ADMINS_DETAIL = 'FETCH_ADMINS_DETAIL';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const ADD_NEW_ADMIN = 'ADD_NEW_ADMIN';


export const FETCH_MEMBER = 'FETCH_MEMBER';


export const FETCH_CONFIG_MAIN = 'FETCH_CONFIG_MAIN';
export const UPDATE_CONFIG_MAIN = 'UPDATE_CONFIG_MAIN';
export const FETCH_CONFIG_DATA = 'FETCH_CONFIG_DATA';
export const UPDATE_CONFIG_DATA = 'UPDATE_CONFIG_DATA';


export const FETCH_RULES = 'FETCH_RULES';
export const UPDATE_RULES = 'UPDATE_RULES';


export const FETCH_SEVERITIES = 'FETCH_SEVERITIES';
export const FETCH_SEVERITY = 'FETCH_SEVERITY';
export const DELETE_SEVERITY = 'DELETE_SEVERITY';
export const UPDATE_SEVERITY = 'UPDATE_SEVERITY';
export const ADD_SEVERITY = 'ADD_SEVERITY';


export const FETCH_FILTER_WORDS = 'FETCH_FILTER_WORDS';
export const ADD_FILTERED_WORD = 'ADD_FILTERED_WORD';
export const UPDATE_FILTERED_WORD = 'UPDATE_FILTERED_WORD';
export const DELETE_FILTERED_WORD = 'DELETE_FILTERED_WORD';

export const FETCH_FILTER_LINKS = 'FETCH_FILTER_LINKS';
export const ADD_WHITELISTED_LINK= 'ADD_WHITELISTED_LINK';
export const UPDATE_WHITELISTED_LINK = 'UPDATE_WHITELISTED_LINK';
export const DELETE_WHITELISTED_LINK = 'DELETE_WHITELISTED_LINK';

export const FETCH_IMMORTALS = 'FETCH_IMMORTALS';
export const FETCH_IMMORTAL = 'FETCH_IMMORTAL';
export const DEACTIVATE_IMMORTAL = 'DEACTIVATE_IMMORTAL';


export const FETCH_MINECRAFT_PLAYER = 'FETCH_MINECRAFT_PLAYER';

export const FETCH_MINECRAFT_STATUS = 'FETCH_MINECRAFT_STATUS';