export const FETCH_ADMIN = 'FETCH_ADMIN';
export const FETCH_GUILD_INFO = 'FETCH_GUILD_INFO';
export const FETCH_RECENT_PUNISHMENTS = 'FETCH_RECENT_PUNISHMENTS';
export const FETCH_ADMINS = 'FETCH_ADMINS';
export const FETCH_MEMBER = 'FETCH_MEMBER';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const ADD_NEW_ADMIN = 'ADD_NEW_ADMIN';